name: build
on: [push]
jobs:
    preview_deploy:
        name: Deploy to preview page
        runs-on: ubuntu-22.04
        if: startsWith(github.ref, 'refs/tags/preview-')
        steps:
            - uses: actions/checkout@v3
            - name: rsync to conoha
              uses: burnett01/rsync-deployments@5.2
              with:
                  switches: -auz --delete --exclude-from="deploy-exclude-files.txt"
                  path: ./
                  remote_path: ${{ secrets.CONOHA_PREVIEW_DEPLOY_PATH }}
                  remote_port: ${{ secrets.CONOHA_SSH_PORT }}
                  remote_host: meigetsu.jp
                  remote_user: Kamioda
                  remote_key: ${{ secrets.DEPLOYSSHKEY }}
    release_deploy:
        name: Deploy to preview page
        runs-on: ubuntu-22.04
        if: startsWith(github.ref, 'refs/tags/release-')
        steps:
            - uses: actions/checkout@v3
            - name: rsync to conoha
              uses: burnett01/rsync-deployments@5.2
              with:
                  switches: -auz --delete --exclude-from="deploy-exclude-files.txt"
                  path: ./
                  remote_path: ${{ secrets.CONOHA_DEPLOY_PATH }}
                  remote_port: ${{ secrets.CONOHA_SSH_PORT }}
                  remote_host: meigetsu.jp
                  remote_user: Kamioda
                  remote_key: ${{ secrets.DEPLOYSSHKEY }}
