name: build
on: [push]
jobs:
  build_test:
    name: React build test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install
      - run: npm run build
  deploy_dev:
    name: Deploy to preview page
    runs-on: ubuntu-22.04
    needs: build_test
    if: startsWith(github.ref, 'refs/tags/preview-')
    steps:
      - uses: actions/checkout@v3
      - name: rsync to conoha
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: |
          npm install
          npm run build
      - name: create ssh key
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYSSHKEY }}
      - name: ready upload
        run: cp ./serverapp/iis.config ./build/web.config
      - name: upload build data
        run: rsync -auz -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.CONOHA_SSH_PORT }}" --delete ./build/ ${{ secrets.CONOHA_USERNAME }}@${{ secrets.CONOHA_SERVER_DOMAIN }}:${{ secrets.CONOHA_DEVDEPLOY_PATH }}
  deploy_release:
    name: Deploy to main page
    runs-on: ubuntu-22.04
    needs: build_test
    if: startsWith(github.ref, 'refs/tags/release-')
    steps:
      - uses: actions/checkout@v3
      - name: rsync to conoha
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: |
          npm install
          npm run build
      - name: create ssh key
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYSSHKEY }}
      - name: ready upload
        run: cp ./serverapp/iis.config ./build/web.config
      - name: upload build data
        run: rsync -auz -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.CONOHA_SSH_PORT }}" --delete ./build/ ${{ secrets.CONOHA_USERNAME }}@${{ secrets.CONOHA_SERVER_DOMAIN }}:${{ secrets.CONOHA_DEPLOY_PATH }}
